# Generated by Django 2.2.6 on 2019-11-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'male')])),
                ('cholesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')])),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sbp', models.IntegerField()),
                ('dbp', models.IntegerField()),
                ('gluc', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')])),
                ('smoke', models.IntegerField(choices=[(0, 'Smoker'), (1, 'Non Smoker')])),
                ('alco', models.IntegerField(choices=[(0, 'Drinks'), (1, 'Non Drinker')])),
                ('active', models.IntegerField(choices=[(0, 'Active Person'), (1, 'Non Active Person')])),
                ('bmi', models.IntegerField(null=True)),
                ('bpc', models.IntegerField(null=True)),
                ('cardio', models.IntegerField(null=True)),
            ],
        ),
    ]
